name: Build torch

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    env:
      CMAKE_BUILD_TYPE: Debug
      BUILD_TEST: "0"

      USE_CUDA: "0"
      USE_ROCM: "0"
    steps:
      - name: Enable Git long paths
        shell: pwsh
        run: |
          git config --global core.longpaths true
      - name: setup uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4
        with:
          python-version: "3.12"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: test msbuild
        shell: pwsh
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\Launch-VsDevShell.ps1" -Arch amd64
          cl
          
      - name: Checkout torch
        uses: actions/checkout@v6
        with:
          repository: pytorch/pytorch
          ref: v2.14.0
          fetch-depth: 1
          submodules: recursive
      
      - name: build
        shell: pwsh
        run: |
          Import-Module Microsoft.VisualStudio.DevShell.dll
          Enter-VsDevShell -VsInstanceId (Get-VsSetupInstance | Select-Object -First 1 -ExpandProperty InstanceId) -DevCmdArguments "-arch=x64"
          uv sync
          .\.venv\Scripts\Activate.ps1
          uv pip install pip
          python setup.py develop
      - name: Upload torch build
        uses: actions/upload-artifact@v7
        with:
          name: torch
          path: build
      
